/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bookshelf: typeof import('./src/components/pages/Bookshelf.vue')['default']
    Bookstore: typeof import('./src/components/pages/Bookstore.vue')['default']
    Category: typeof import('./src/components/pages/Category.vue')['default']
    CategoryDetail: typeof import('./src/components/pages/CategoryDetail.vue')['default']
    Child: typeof import('./src/components/pages/Child.vue')['default']
    Classic: typeof import('./src/components/pages/Classic.vue')['default']
    Discovery: typeof import('./src/components/pages/Discovery.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElText: typeof import('element-plus/es')['ElText']
    Foot: typeof import('./src/components/common/Foot.vue')['default']
    Head: typeof import('./src/components/common/Head.vue')['default']
    HighScore: typeof import('./src/components/pages/HighScore.vue')['default']
    Knowledge: typeof import('./src/components/pages/Knowledge.vue')['default']
    Latest: typeof import('./src/components/pages/Latest.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    LookHistories: typeof import('./src/components/pages/lookHistories.vue')['default']
    Mine: typeof import('./src/components/pages/Mine.vue')['default']
    New: typeof import('./src/components/pages/New.vue')['default']
    Newest: typeof import('./src/components/pages/Newest.vue')['default']
    Recommend: typeof import('./src/components/pages/Recommend.vue')['default']
    Reply: typeof import('./src/components/remark/Reply.vue')['default']
    Root: typeof import('./src/components/remark/Root.vue')['default']
    RootRemark: typeof import('./src/components/pages/remark/RootRemark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/pages/Search.vue')['default']
    Topic: typeof import('./src/components/pages/Topic.vue')['default']
    TopicDetail: typeof import('./src/components/pages/TopicDetail.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanNotify: typeof import('vant/es')['Notify']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
