/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/common/Home.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    Register: typeof import('./src/components/pages/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDialog: typeof import('vant/es')['Dialog']
  }
}
